#!/bin/sh
cat /sys/class/power_supply/BAT1/{status,capacity} | tr '\n' ' ' | {
    read -r status capacity
    echo "$(date) Current battery ${status} ${capacity}" >> /var/log/acpid.log

    if [ "${status}" = 'Discharging' -a "${capacity}" -lt 15 ]
    then
        /usr/bin/logger "Critical battery threshold"
        /usr/bin/systemctl hibernate
    fi
}
